# Generated by Django 2.0.6 on 2018-06-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=30)),
                ('dept_id', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('sub_code', models.CharField(max_length=10)),
                ('tech_id', models.CharField(max_length=10)),
            ],
        ),
    ]
