# Generated by Django 2.0.6 on 2018-06-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0003_auto_20180630_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='tech_id',
            new_name='teac_id',
        ),
    ]
